name: Build

on:
  push:
    branches:
      - '**'



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ccc
        uses: actions/checkout@v3
        with:
          repository: pawelbanasiak/github-actions
          path: mt
      - name: dupa
        uses: mt/actions/compress@v1
        with:
          dir: dupa
      - name: test
        run: echo "${GITHUB_REF_NAME}"
