name: Build

on:
  push:
    branches:
      - '**'



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ccc
        uses: actions/checkout@v3
        with:
          repository: pawelbanasiak/github-actions
      - name: dupa
        uses: ./.github/actions/compress
        with:
          dir: dupa-dir
      - name: test
        run: echo "${GITHUB_REF_NAME}"


